### ISSUE TITLE
Documentation build of pptable failed silently

### ISSUE THREAD

**Issue by bgamari** [haskell/hackage-server#546]
[Here](https://hackage.haskell.org/package/pptable) we see that the documentation build for the upload of the initial version of the `pptable` package failed, yet the build remains in "Docs pending" state. This is quite odd as the build did not fail due to a missing target like in #543. Instead, the issue is just a run-of-the-mill build error,

```
Building pptable-0.1.0.0...
Preprocessing library pptable-0.1.0.0...
[1 of 2] Compiling Text.PrettyPrint.Tabilize ( src/Text/PrettyPrint/Tabilize.hs, dist/build/Text/PrettyPrint/Tabilize.o )

src/Text/PrettyPrint/Tabilize.hs:141:3: error:
    • Constraint ‘Data a’ in the type of ‘printMap’
        constrains only the class type variables
      Use ConstrainedClassMethods to allow it
    • When checking the class method:
        printMap :: forall a.
                    Tabilize a =>
                    forall b. (Show b, Data a) => Map.Map b a -> IO ()
      In the class declaration for ‘Tabilize’

src/Text/PrettyPrint/Tabilize.hs:158:3: error:
    • Constraint ‘Data a’ in the type of ‘printList’
        constrains only the class type variables
      Use ConstrainedClassMethods to allow it
    • When checking the class method:
        printList :: forall a. (Tabilize a, Data a) => [a] -> IO ()
      In the class declaration for ‘Tabilize’

src/Text/PrettyPrint/Tabilize.hs:176:3: error:
    • Constraint ‘Data a’ in the type of ‘printVector’
        constrains only the class type variables
      Use ConstrainedClassMethods to allow it
    • When checking the class method:
        printVector :: forall a.
                       (Tabilize a, Data a) =>
                       V.Vector a -> IO ()
      In the class declaration for ‘Tabilize’
cabal: Leaving directory '/tmp/cabal-tmp-17716/pptable-0.1.0.0'
Failed to install pptable-0.1.0.0
cabal: Error: some packages failed to install:
pptable-0.1.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

Usually `hackage-server` notices when a package fails to build like this. It's totally unclear why it didn't in this particular case.

**Comment by domenkozar** [comment]
Simlar for https://hackage.haskell.org/package/haquery-0.1.1.3/, still "pending".

**Comment by gbaz** [comment]
@bgamari we've changed the builder since this issue, and we don't seem to have had a repeat? do you think its worth leaving open?

**Comment by bgamari** [comment]
gbaz <notifications@github.com> writes:

> @bgamari we've changed the builder since this issue, and we don't seem
> to have had a repeat? do you think its worth leaving open?
>
I'd say close it; it can always be reopened if it occurs again.
