### ISSUE TITLE
Build error of current `master` caused by `haddock-library-1.11.0`

### ISSUE THREAD

**Issue by andreasabel** [haskell/hackage-server#1128]
Current `master` (c84f467c2453e59f6bfd24f06ee3615befddcb18) fails to build with GHC 9.2.4 in the latest ecosystem:
```
$ cabal build
Build profile: -w ghc-9.2.4 -O1
...
[ 31 of 181] Compiling Distribution.Server.Pages.Package.HaddockHtml ( ... )

src/Distribution/Server/Pages/Package/HaddockHtml.hs:27:25: error:
    • No instance for (HTML (Int, Html))
        arising from a use of ‘ordList’
    • In the ‘markupOrderedList’ field of a record
      In the expression:
        Markup
          {markupEmpty = noHtml, markupString = toHtml,
           ...
           markupOrderedList = ordList, markupDefList = defList,
          ...
           markupTable = \ (Table h r) -> makeTable h r}
      In an equation for ‘htmlMarkup’: ...
         
   |
27 |   markupOrderedList   = ordList,
   |                         ^^^^^^^
```
This is the used dependencies according to `cabal-plan`:
```
  Cabal-3.6.3.0
  HStringTemplate-0.8.8
  HTTP-4000.3.16
  QuickCheck-2.14.2
  array-0.5.4.0
  base-4.15.1.0
  binary-0.8.8.0
  blaze-builder-0.4.2.2
  blaze-html-0.9.1.2
  base16-bytestring-1.0.2.0
  base64-bytestring-1.2.1.0
  bytestring-0.10.12.1
  acid-state-0.16.1.1
  commonmark-0.2.2
  commonmark-extensions-0.2.3.2
  containers-0.6.4.1
  cereal-0.5.8.3
  cryptohash-md5-0.11.101.0
  cryptohash-sha256-0.11.102.1
  csv-0.1.2
  ed25519-0.0.5.0
  deepseq-1.4.5.0
  directory-1.3.6.2
  filepath-1.4.2.1
  fail-4.9.0.0
  hackage-security-0.6.2.2
  hackage-security-HTTP-0.1.1.1
  haddock-library-1.11.0
  happstack-server-7.7.2
  hashable-1.4.1.0
  hslogger-1.3.1.0
  lifted-base-0.2.3.12
  mime-mail-0.5.1
  mtl-2.2.2
  unordered-containers-0.2.19.1
  network-3.1.2.7
  network-bsd-2.8.1.0
  network-uri-2.6.4.1
  parsec-3.1.14.0
  pretty-1.1.3.6
  process-1.6.13.2
  random-1.2.1.1
  rss-3000.2.0.7
  scientific-0.3.7.0
  safecopy-0.10.4.2
  semigroups-0.19.2
  aeson-2.0.3.0
  snowball-1.0.0.1
  split-0.2.3.5
  stm-2.5.0.0
  async-2.2.4
  text-1.2.5.0
  tagged-0.8.6.1
  time-1.9.3
  tokenize-0.3.0
  tar-0.5.1.1
  transformers-0.5.6.2
  attoparsec-0.14.4
  attoparsec-iso8601-1.0.2.1
  unix-2.7.2.2
  vector-0.12.3.1
  xhtml-3000.2.2.1
  xmlgen-0.6.2.2
  xss-sanitize-0.3.7
  zlib-0.6.3.0
```

**Comment by andreasabel** [comment]
Looks like `haddock-library` changed the type of `markupOrderedList`: https://hackage.haskell.org/package/haddock-library-1.11.0/docs/Documentation-Haddock-Types.html#t:DocMarkupH
